name: Deploy GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - "site/**"
      - "docs/images/**"
      - ".github/workflows/pages.yml"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: false


jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:

      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4


      # 构建静态站点
      - name: Prepare static site
        run: |
          rm -rf dist
          mkdir -p dist/docs

          cp site/index.html dist/index.html
          cp -r docs/images dist/docs/images


      # 初始化 Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5


      # 上传静态文件
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist


      # 发布
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
